# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc8a63be9e1280c3d9a21d7fca18853e9ae5f60f5874ff1beffabbecfc8209aaaaee3b40b48f3db2f5b32a4cac378ac6bf12d1622f6c8296e5996e299e7a1133

test:
  secret_key_base: 4b4de0ee54f28a7ab77a1f3f757619189d5488c41a7352941c71d50b80b6e65f99ba86a528edaa62c8f9a59753829c9497be0d2c12360363202812231d830586

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
